
name: creating matrixes

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  step_7_download_matrixes:
    # The type of runner that the job will run on
  step_7_download_matrixes:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        bug_ind: [33] #[19, 28, 29, 45, 49, 83, 224, 229, 259, 262, 284, 21, 27, 30, 31, 32, 33, 34, 36, 48, 54, 56, 57, 68, 72, 73, 76, 78, 87, 90, 176, 178, 181, 182, 183, 200, 219, 225, 230, 248, 249, 252, 258, 267, 269, 275, 279, 282, 283, 289, 290, 291, 296, 305, 306, 307, 309, 311, 312, 314, 315, 317, 319, 321, 325]



    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat maven
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install junitparser
          pip install networkx
          pip install pytest 
          pip install gitpython
          pip install jira
          pip install termcolor 
          pip install openpyxl  
          pip install javalang
          pip install pathlib
          pip install junitparser
          pip install numpy
          pip install sklearn
          pip install pandas
          pip install pyswarm
          pip install networkx
          pip install lizard
          pip install jsons
      - name: Checkout d4j
        uses: actions/checkout@v2
        with:
          repository: amir9979/defects4j
          path: .
          fetch-depth: 0
      
      - name: Checkout javadiff
        uses: actions/checkout@v2
        with:
          repository: amir9979/javadiff
          path: ./framework/bug-mining/tracing/javadiff
          fetch-depth: 0

      - name: Checkout sfl
        uses: actions/checkout@v2
        with:
          repository: amir9979/sfl
          path: ./framework/bug-mining/tracing/sfl
          fetch-depth: 0

      - run: cpanm --installdeps .
      - run: ./init.sh

      - name: initialize-project-and-collect-issues
        run: ./initialize-project-and-collect-issues.pl -p Lang -n commons-lang -w bug-mining_${{ matrix.bug_ind }} -r https://github.com/apache/commons-lang.git -g jira -t LANG -e "/(LANG-\d+)/mi"
        working-directory: ./framework/bug-mining
      
      - name: initialize-revisions
        run: ./initialize-revisions.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}  -i ${{ matrix.bug_ind }} 
        working-directory: ./framework/bug-mining

      - name: analyze-project
        run: ./analyze-project.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}  -g jira -t LANG -i ${{ matrix.bug_ind }} 
        working-directory: ./framework/bug-mining

      - name: get-trigger
        run: ./get-trigger.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}
        working-directory: ./framework/bug-mining

      - name: get-metadata
        run: ./get-metadata.pl -p Lang -w bug-mining_${{ matrix.bug_ind }}
        working-directory: ./framework/bug-mining

      - name: delete repo
        if: ${{always()}}
        run: |
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/project_repos
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/issues
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/framework/core
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/gitlog
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/issues.txt
            rm -rf ./framework/bug-mining/bug-mining_${{ matrix.bug_ind}}/framework/projects/Lang/lib
            rm -rf ./framework/bug-mining/tracing
      
      
      - name: create dir matrixes
        run: |
              cd ./framework/bug-mining
              mkdir matrixes_before_change
              
      - name: Script
        run: |
              import os
              active_bugs = False
              path = os.path.join('.','framework','bug-mining')
              a= os.listdir(path)
              print(a)
              for file in a:
                  if 'bug-mining' in file:
                      p = os.path.join(path,file)
                      old = os.path.join(p,'framework', 'projects','Lang',f"matrix_{file.split('_')[1]}.json")
                      new = os.path.join(path,"matrixes_before_change",f"{file.split('_')[1]}.json")
                      os.rename(old,new)
                      if not active_bugs:
                          active_bugs = True
                          os.rename(os.path.join(p,'framework', 'projects','Lang',"active-bugs.csv"),os.path.join(path,"matrixes_before_change","active-bugs.csv"))
        shell: python
      
      - name: Upload bug-mining
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: step_7_artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./framework/bug-mining/matrixes_before_change
